### ISSUE TITLE
Broken Login Controller

### ISSUE THREAD

**Issue by kibetrns** [kori-njoroge/social-media-nodejs-server#3]
Despite providing the correct credentials, a user is not successfully logged in.

**Comment by kori-njoroge** [comment]
what credentials did you use?

**Comment by kibetrns** [comment]
I had used the credentials from the default data rows that that come with the schema in `objects.sql` . It was failing because of the  the rows that are inserted are not encrypted. The inserted dummy data that comes in the `objects.sql` should be removed , to avoid this.

**Comment by kibetrns** [comment]
Fixed with this [commit](https://github.com/kori-njoroge/social-media-nodejs-server/commit/ed52224f22a63b40c6a114989745098f8c275803)  and [this](https://github.com/kori-njoroge/social-media-nodejs-server/commit/9fadf0c4b98837828e44d1724e34b764a62292d0) commit and [this](https://github.com/kori-njoroge/social-media-nodejs-server/commit/9e7db84388d25c54bddc3248c3e913eb2602154b) one.
